version: "3"

services:
  app:
    build:
      context: . # Substitua pelo caminho para o diretório do Symfony
      dockerfile: Dockerfile # Nome do Dockerfile para o Symfony
    ports:
      - "80:80" # Mapeamento de porta do Symfony
    volumes:
      - .:/var/www/ # Mapear o código-fonte do Symfony para o contêiners
    networks:
      - default
    depends_on:
      - db
    links:
      - db

  db:
    image: "mysql:8.0"
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "/var/lib/mysql"
      - "mysql:/var/lib/mysql"
      - "./apache/:/docker-entrypoint-initdb.d"
    networks:
      - default
networks:
  default:
    driver: bridge
volumes:
  mysql:
    driver: local
