version: "3"
services:
  # Configuração do serviço para a API Symfony
  api:
    container_name: api
    build:
      context: . # Diretório onde o código Symfony está localizado
      dockerfile: Dockerfile # Use o Dockerfile do Symfony
    ports:
      - "80:80" # Mapeie a porta 80 para a API Symfony
    volumes:
      - .:/api # Monte a pasta da API Symfony no contêiner
    depends_on:
      - db # Dependência opcional de um serviço de banco de dados
    links:
      - db
  # Configuração do serviço para um banco de dados (opcional)
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - "/var/lib/mysql"
      - "mysql:/var/lib/mysql"
      - "/apache/:/docker-entrypoint-initdb.d"
# Outras configurações, como volumes, redes, etc., podem ser adicionadas conforme necessário.
volumes:
  mysql:
    driver: local
