version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_ROOT_DATABASE: '${DB_DATABASE}'
        MYSQL_ROOT_USER: '${DB_USERNAME}'
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1  
    volumes:
      - /var/lib/mysql
      - db_data:/var/lib/mysql
volumes:
   db_data: