version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - db
    volumes:
      - .:/var/www/html
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PASSWORD=1234
    links:
      - db
    networks:
      - default
  db:
    image: mysql:8.0
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: corretora
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - /var/lib/mysql
      - db_data:/var/lib/mysql
networks:
    default:
        driver: bridge
volumes:
   db_data: